### ISSUE TITLE
周目数识别失败

### ISSUE THREAD

**Issue by suisankasuiso** [Metric-Void/PCR-GuildBot#1]
使用“统计 队伍=<队名> [周目=<数字>] [BOSS=<数字>]”指令时，不论参数如何，始终出现周目数识别失败
![QQ图片20200529231811](https://user-images.githubusercontent.com/44424195/83276159-c9f2fa80-a202-11ea-9e4d-0d62ef7f0504.png)

**Comment by Metric-Void** [comment]
已在v1.0.5中修复并更新，谢谢反馈！
https://github.com/Metric-Void/PCR-GuildBot/releases/tag/v1.0.5

（确认修复后请close issue）

**Comment by Metric-Void** [comment]
两天了 先close了
